
# API đăng nhập
# POST http://localhost:3001/auth/login
# Content-Type: application/json

# {
#     "username":"minhtam2",
#     "password":"12345678",
#     "type":"admin"
# }

# API lấy thông tin các nhân
# GET http://localhost:3001/branches/theaters
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwYjQ3YmFmLWIyZGMtNGY5NS05Nzk0LWUyODcwYjZiZTk2NSIsInJvbGUiOiJhZG1pbiIsInN0YXR1cyI6ImlzTG9naW5nIiwiaWF0IjoxNzgxODMzNDkwLCJleHAiOjE3ODE4NjIyOTB9.37ekhJVls_nzmllqpwupU-Osl44odJZx9HAsoWdB09E

# GET http://localhost:3001/branches/chairs/3
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwYjQ3YmFmLWIyZGMtNGY5NS05Nzk0LWUyODcwYjZiZTk2NSIsInJvbGUiOiJhZG1pbiIsInN0YXR1cyI6ImlzTG9naW5nIiwiaWF0IjoxNzgxNzczNzIwLCJleHAiOjE3ODE3NzQ2MjB9._0JBlU0FVj58Iqo41Ky-PFv8AUQmZaatEP7ya9Pp1ok

// API tạo mới phòng chiếu, tạo luôn phòng chiếu
# POST  http://localhost:3001/branches/room
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwYjQ3YmFmLWIyZGMtNGY5NS05Nzk0LWUyODcwYjZiZTk2NSIsInJvbGUiOiJhZG1pbiIsInN0YXR1cyI6ImlzTG9naW5nIiwiaWF0IjoxNzgxODMzNDkwLCJleHAiOjE3ODE4NjIyOTB9.37ekhJVls_nzmllqpwupU-Osl44odJZx9HAsoWdB09E
# Content-Type: application/json

# {
#     "name":"Phòng chiếu số tạm 2",
#     "type":3,
#     "countStandard": 1,
#     "countVIP": 1,
#     "countSweetbox": 1,
#     "arrName":[["A"],["C"],["F"]],
#     "arrType":["Standard","VIP","Sweetbox"],
#     "chairPerLine":4
# }


#GET http://localhost:3001/branches/type/theater

# DELETE http://localhost:3001/branches/theaters/1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwYjQ3YmFmLWIyZGMtNGY5NS05Nzk0LWUyODcwYjZiZTk2NSIsInJvbGUiOiJhZG1pbiIsInN0YXR1cyI6ImlzTG9naW5nIiwiaWF0IjoxNzgxODMzNDkwLCJleHAiOjE3ODE4NjIyOTB9.37ekhJVls_nzmllqpwupU-Osl44odJZx9HAsoWdB09E

