// API lất toàn bộ phim
# GET http://localhost:3001/movies/all
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwYjQ3YmFmLWIyZGMtNGY5NS05Nzk0LWUyODcwYjZiZTk2NSIsInJvbGUiOiJhZG1pbiIsInN0YXR1cyI6ImlzTG9naW5nIiwiaWF0IjoxNzgwOTkyODAyLCJleHAiOjE3ODEwNzkyMDJ9.6lGVtkaZ3Cvn_j_TipiFQJ8OBqOlS78gIOliY0V-uDs

# GET http://localhost:3001/movies/showtime
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwYjQ3YmFmLWIyZGMtNGY5NS05Nzk0LWUyODcwYjZiZTk2NSIsInJvbGUiOiJhZG1pbiIsInN0YXR1cyI6ImlzTG9naW5nIiwiaWF0IjoxNzgxODMzNDkwLCJleHAiOjE3ODE4NjIyOTB9.37ekhJVls_nzmllqpwupU-Osl44odJZx9HAsoWdB09E

// API thêm mới phim 
# POST  http://localhost:3001/movies
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwYjQ3YmFmLWIyZGMtNGY5NS05Nzk0LWUyODcwYjZiZTk2NSIsInJvbGUiOiJhZG1pbiIsInN0YXR1cyI6ImlzTG9naW5nIiwiaWF0IjoxNzgwOTA1OTYwLCJleHAiOjE3ODA5OTIzNjB9.zVvnF4B3o7Z6omjoIRLiEM78CYNyHVXzF7T-15R9Gkk

# {
#     "title":"Tế xác",
#     "duration":120,
#     "release_date": "2026-06-10 8:00:00",
#     "poster_url":"https://upload.wikimedia.org/wikipedia/vi/f/fe/Poster_phim_t%E1%BA%BF_x%C3%A1c_2014.jpg",
#     "trailer_url":null,
#     "categories": [3,4]
# }

// API sửa phim 
# PUT  http://localhost:3001/movies
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwYjQ3YmFmLWIyZGMtNGY5NS05Nzk0LWUyODcwYjZiZTk2NSIsInJvbGUiOiJhZG1pbiIsInN0YXR1cyI6ImlzTG9naW5nIiwiaWF0IjoxNzgwOTczNDIxLCJleHAiOjE3ODEwNTk4MjF9.bzDY-H8S6zpt07Y89iBdvfCTAqzayD8w0FG-LTLrwkY

# {
#     "id":20,
#     "title":"Tế xác",
#     "duration":120,
#     "release_date": "2026-06-10 8:00:00",
#     "poster_url":"https://upload.wikimedia.org/wikipedia/vi/f/fe/Poster_phim_t%E1%BA%BF_x%C3%A1c_2014.jpg",
#     "trailer_url":null,
#     "categories": [3,4]
# }


// API xóa phim 
# DELETE  http://localhost:3001/movies/2
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwYjQ3YmFmLWIyZGMtNGY5NS05Nzk0LWUyODcwYjZiZTk2NSIsInJvbGUiOiJhZG1pbiIsInN0YXR1cyI6ImlzTG9naW5nIiwiaWF0IjoxNzgwOTA1OTYwLCJleHAiOjE3ODA5OTIzNjB9.zVvnF4B3o7Z6omjoIRLiEM78CYNyHVXzF7T-15R9Gkk


# POST  http://localhost:3001/movies
# Content-Type: application/json

# {
#     "title":"Tử chiến trên không 5",
#     "duration":120,
#     "release_date": "2026-05-30 19:00:00"
# }

// API sửa thông tin chi nhánh
# POST  http://localhost:3001/branches/
# Content-Type: application/json

# {
#     "name":"Ho Chi Minh CineSTU",
#     "address":"123 Nguyen Van Linh Street, District 7, Ho Chi Minh City"
# }



